version: "3.9"
services:
  db:
    image: "postgres:15"
    environment:
      POSTGRES_DB: "DB"              # .env (POSTGRES_DB)
      POSTGRES_USER: "USER"          # .env (POSTGRES_USER)
      POSTGRES_PASSWORD: "PASSWORD"  # .env (POSTGRES_PASSWORD)
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
